version: '3'

services:
  web:
    restart: always
    build: ./midas
    ports:
      - "9000:8000"
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
    env_file:
      - .env
    environment:
      DEBUG: 'true'
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  web-django:
  web-static: